services:
  - type: web
    name: zalepa.art
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
databases:
  - name: production
    plan: free
    postgresMajorVersion: 14
